apiVersion: v1
kind: Service
metadata:
  name: {{ include "pathfinding.fullname" . }}-logic
  labels:
    {{- include "pathfinding.labels" . | nindent 4 }}
spec:
  type: {{ .Values.logic.service.type }}
  ports:
    - port: {{ .Values.logic.service.logicport }}
      targetPort: pathfindinglogic
      protocol: TCP
      name: pathfindinglogic
  selector:
    {{- include "pathfinding.selectorLabels" . | nindent 4 }}
    app: {{ include "pathfinding.fullname" . }}-logic

