imagePullSecrets: 

logic:
  replicaCount: 1
  service: 
    type: ClusterIP
    type: LoadBalancer
    logicport: 8050
    persistport: 8051
  image:
    repository: docker.pkg.github.com/maana-io/maana-ai-pathfinding-js/maana-ai-pathfinding-js
    pullPolicy: IfNotPresent
  version: 869f1d2 

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ckg: {}
  # url

auth: {}
  # provider
  # audience
  # identifier
  # client-identifier
  # domain
  # secret


